### ISSUE TITLE
$this & search

### ISSUE THREAD

**Issue by dgoosens** [robertbasic/pugdebug#175] opened 2016-07-28 08:13 UTC
hi

Am giving pugdebug a try...  
Thing I don't understand is why `$this` does not appear in the variables tab.
Creating a Expression with `$this` does work though but figure it should be available automatically when in a class.

Likewise, I think it would make sense to have things like `$_SERVER` available automatically as well.

A part from that there is really one feature that is missing, and very annoying...  
A search function... 
- for a file in active projects
- for text in active file

Great job!

**Comment by robertbasic** [comment] 2017-01-02 10:31
For `$this`, I replied in #173 that I do see it.

The `$_SERVER` and other superglobals are accessible in the "Superglobals" tab:

![screenshot_2017-01-02_11-29-12](https://cloud.githubusercontent.com/assets/166625/21587630/e281a0fe-d0de-11e6-828c-19814b0020a9.png)

I'll create a new issue for the search feature request, that sounds useful indeed.

Thanks!

**Comment by robertbasic** [comment] 2017-01-02 10:31
Closing as a duplicate of #173

**Closed by robertbasic** 2017-01-02 10:31 UTC
Labels: bug

**Comment by robertbasic** [comment] 2017-01-08 11:20
@dgoosens searching for files is now in master, thanks for the request!
